In [6]:
import numpy as np
a = np.array([[3.25,7.19,8.66,7.36],
             [9.35,7.26,4.76,7.61],
             [1.75,5.15,3.60,7.88],
             [5.45,6.29,3.22,7.19]])


In [7]:
print (a.shape)

(4, 4)


In [8]:
a[2,2]

3.6

In [9]:
a[2,:]#:son totes les columnes o les files

array([1.75, 5.15, 3.6 , 7.88])

In [10]:
a.reshape(8,2)

array([[3.25, 7.19],
       [8.66, 7.36],
       [9.35, 7.26],
       [4.76, 7.61],
       [1.75, 5.15],
       [3.6 , 7.88],
       [5.45, 6.29],
       [3.22, 7.19]])

In [11]:
print (a.min())

1.75


In [12]:
print (a.max())

9.35


In [13]:
print (a.min(0))

[1.75 5.15 3.22 7.19]


In [14]:
print(a.min(1))

[3.25 4.76 1.75 3.22]


In [16]:
b=a.reshape(1,16) #pasem tota la matriu a una única fila
print(b)
a.argmax() #busquem la posició del valor més alt

[[3.25 7.19 8.66 7.36 9.35 7.26 4.76 7.61 1.75 5.15 3.6  7.88 5.45 6.29
  3.22 7.19]]


4

In [22]:
print (a.argmax(0))#de cada columna
print (a.argmax(1))#de cada fila
print (a)

[1 1 0 2]
[2 0 3 3]
[[3.25 7.19 8.66 7.36]
 [9.35 7.26 4.76 7.61]
 [1.75 5.15 3.6  7.88]
 [5.45 6.29 3.22 7.19]]


In [26]:
a.ndim
c=a.reshape(-1,1) #aplanar tot per tenir una única dimensió (-1) el segon 1 es per que aquesta dimensió sigui una columna, si no es posa (c=a.reshape(-1) sería una fila, pero la IA treballa amb columnes.
c.ndim
print(c)

[[3.25]
 [7.19]
 [8.66]
 [7.36]
 [9.35]
 [7.26]
 [4.76]
 [7.61]
 [1.75]
 [5.15]
 [3.6 ]
 [7.88]
 [5.45]
 [6.29]
 [3.22]
 [7.19]]
